<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */

/** @var HeroiconsOutline $heroiconsOutline */
$heroiconsOutline = $viewModels->require(HeroiconsOutline::class);

?>

<template x-if="searchResult.type == 'product_add_to_cart'">
    <a class="w-full block" :href="searchResult.url" :title="searchResult.title">
        <div class="grid grid-cols-5 gap-4 p-3">
            <div class="col-span-1 m-auto">
                <img :src="searchResult.image" class="inline-block"/>
            </div>
            <div class="col-span-2">
                <span class="text-sm" x-text="searchResult.title"></span>
                <span class="text-sm font-bold" x-html="searchResult.price"></span>
            </div>
            <div class="col-span-2 content-end items-end">
                <form method="post" :name="searchResult.form_name"
                      x-bind:action="searchResult.add_url">
                    <input name="form_key" type="hidden" x-bind:value="searchResult.formkey">
                    <input name="return_url" type="hidden" value="<?= $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>">
                    <input name="qty" @click.prevent=""
                           class="px-2 py-2 w-12 sm:w-20 text-center invalid:ring-2 invalid:ring-red-500 inline-block rounded border-gray-300"
                           :min="searchResult.qty_min"
                           :max="searchResult.qty_max"
                           :step="searchResult.qty_step"
                           x-bind:value="searchResult.qty_min"
                           :type="searchResult.qty_format.type"
                           :pattern="searchResult.qty_format.pattern"
                           :inputmode="searchResult.qty_format.mode"
                    />
                    <button class="btn btn-primary inline-block text-base"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
                        <div class="inline">
                        <?= $heroiconsOutline->shoppingCartHtml("h-6 w-6 border-current", 25, 25) ?>
                        </div>
                    </button>
                </form>
            </div>
        </div>
    </a>
</template>
